name: frontend-ci 

on:
  push :
    branches :
      - front-github-action
  pull_request: 
    branches : 
      - front-github-action

jobs:
  build:
    runs-on: ubuntu-latest 
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup node 
        uses: actions/setup-node@v3
        with: 
          node-version: 18.x

      - name: AWS IAM 사용자 설정
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }} 
          aws-region: ap-northeast-2
       
      - name: Run build
        run: |
          yarn install
          export VITE_APP_KAKAO_KEY=${{ secrets.VITE_APP_KAKAO_KEY }}
          export VITE_APP_BASE_URL=${{ secrets.VITE_APP_BASE_URL }}
          yarn run build 

      - name: Upload to S3
        run: aws s3 sync dist s3://mywalkarybucket/ --exclude "node_modules/*" --region ap-northeast-2
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }} 
