name: frontend-ci 

on:
  push :
    branches :
      - develop
  pull_request: 
    branches : 
      - develop

jobs:
  build:
    runs-on: ubuntu-latest 
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup node 
        uses: actions/setup-node@v3
        with: 
          node-version: 18.x

      - name: Install dependencies 
        run: yarn install --immutable
       
      - name: Run build
        run: yarn run build 
       
      - name: Configure AWS credentials
        uses: jakejarvis/s3-sync-action@master 
        with:
          args: --delete
        env :
          AWS_S3_BUCKET: "mywalkarybucket"
          AWS_ACCESS_KEY_ID : ${{secrets.AWS_ACCESS_KEY_ID}}  
          AWS_SECRET_ACCESS_KEY : ${{secrets.AWS_SECRET_ACCESS_KEY}}
          AWS_REGION : ap-northeast-2
          SOURCE_DIR: ./dist

      - name: Upload to S3
        run: aws s3 cp --recursive --region ap-northeast-2 dist s3://mywalkarybucket --exclude "node_modules/*"
